# Generated by Django 3.0a1 on 2019-10-17 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='title')),
                ('slug', models.SlugField(editable=False, verbose_name='slug')),
                ('url', models.URLField(blank=True, max_length=300, verbose_name='url')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('status', models.CharField(choices=[('Published', 'Published')], db_index=True, default='Published', max_length=30, verbose_name='status')),
                ('upvotes', models.IntegerField(default=0, verbose_name='upvotes')),
                ('downvotes', models.IntegerField(default=0, verbose_name='downvotes')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='links.Post', verbose_name='parent post')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='sites.Site', verbose_name='site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='submitter')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'unique_together': {('site', 'slug')},
            },
        ),
    ]
